// ds-case003-canyon — Case 003 "Column Canyon"
// Spec: KQL-Detective-Implementation-Spec.md §7.3
//
// Planted facts (asserted by verify.mjs):
//   Perf rows ..................................... 3456  (12 computers x 96 slots x 3 counters)
//   "% Processor Time" values ..................... 1152, all unique to 2dp
//   Top 5 CPU readings ............................ exactly the table below
//   Every non-planted CPU value ................... <= 94.00

import { QUERY_TIME, iso, mulberry32, round2, timeSlots, writeDataset } from './lib.mjs';

const SPAN_START = '2026-03-10T12:00:00Z';
const SPAN_END = '2026-03-11T11:45:00Z';
const STEP_MINUTES = 15;

const rand = mulberry32(3456003);

const COMPUTERS = [
  'PRD-WEB-01', 'PRD-WEB-02', 'PRD-APP-01', 'PRD-APP-02', 'PRD-SQL-01', 'PRD-WEB-03',
  'PRD-SQL-02', 'PRD-CACHE-01', 'PRD-MON-01', 'DEV-WEB-01', 'DEV-APP-01', 'UAT-APP-01',
];

const COUNTERS = [
  { ObjectName: 'Processor', CounterName: '% Processor Time', InstanceName: '_Total' },
  { ObjectName: 'Memory', CounterName: 'Available MBytes', InstanceName: '_Total' },
  { ObjectName: 'Network Adapter', CounterName: 'Bytes Total/sec', InstanceName: 'eth0' },
];

// The five readings T-003-04 must return, in this exact order.
const PLANTED_TOP5 = [
  { Computer: 'PRD-SQL-01', TimeGenerated: '2026-03-11T09:15:00Z', CounterValue: 99.87 },
  { Computer: 'PRD-APP-01', TimeGenerated: '2026-03-11T09:15:00Z', CounterValue: 98.41 },
  { Computer: 'PRD-WEB-01', TimeGenerated: '2026-03-11T09:00:00Z', CounterValue: 97.62 },
  { Computer: 'PRD-APP-02', TimeGenerated: '2026-03-11T09:15:00Z', CounterValue: 96.15 },
  { Computer: 'PRD-WEB-02', TimeGenerated: '2026-03-11T09:00:00Z', CounterValue: 95.33 },
];
const plantedKey = (c, t) => `${c}|${t}`;
const plantedMap = new Map(PLANTED_TOP5.map((p) => [plantedKey(p.Computer, p.TimeGenerated), p.CounterValue]));

const COLUMNS = [
  { name: 'TimeGenerated', type: 'datetime' },
  { name: 'Computer', type: 'string' },
  { name: 'ObjectName', type: 'string' },
  { name: 'CounterName', type: 'string' },
  { name: 'InstanceName', type: 'string' },
  { name: 'CounterValue', type: 'real' },
];

const slots = timeSlots(SPAN_START, SPAN_END, STEP_MINUTES);

// T-003-04 uses `top 5 by CounterValue desc`, which is only deterministic if no two CPU
// values tie. Enforce uniqueness at 2dp across all 1152 readings.
const usedCpu = new Set(PLANTED_TOP5.map((p) => p.CounterValue));
function uniqueCpuValue() {
  for (let attempt = 0; attempt < 10_000; attempt++) {
    // Ceiling of 94.00 keeps every organic reading below the planted top five.
    const v = round2(5 + rand() * 89);
    if (v <= 94 && !usedCpu.has(v)) {
      usedCpu.add(v);
      return v;
    }
  }
  throw new Error('Exhausted the unique CPU value space — widen the range or lower the sample count.');
}

const rows = [];
for (const computer of COMPUTERS) {
  for (const slot of slots) {
    const time = iso(slot);
    for (const counter of COUNTERS) {
      let value;
      if (counter.CounterName === '% Processor Time') {
        value = plantedMap.get(plantedKey(computer, time)) ?? uniqueCpuValue();
      } else if (counter.CounterName === 'Available MBytes') {
        value = round2(1024 + rand() * 15360);
      } else {
        value = round2(rand() * 125_000_000);
      }
      rows.push({
        TimeGenerated: time,
        Computer: computer,
        ObjectName: counter.ObjectName,
        CounterName: counter.CounterName,
        InstanceName: counter.InstanceName,
        CounterValue: value,
      });
    }
  }
}

rows.sort((a, b) =>
  a.TimeGenerated === b.TimeGenerated
    ? a.Computer.localeCompare(b.Computer) || a.CounterName.localeCompare(b.CounterName)
    : a.TimeGenerated.localeCompare(b.TimeGenerated)
);

writeDataset({
  datasetId: 'ds-case003-canyon',
  tables: { Perf: rows },
  columns: { Perf: COLUMNS },
  readme: `
# ds-case003-canyon

Generated by \`seed/seed-case003.mjs\`. Do not edit by hand.

- **queryTime:** ${QUERY_TIME}
- **Span:** ${SPAN_START} to ${SPAN_END}, one sample every ${STEP_MINUTES} minutes (96 slots)
- **Shape:** 12 computers x 96 slots x 3 counters = 3456 rows

## Planted facts

| Fact | Value |
|------|-------|
| \`Perf\` rows | 3456 |
| \`% Processor Time\` readings | 1152, all unique to 2dp |
| Highest non-planted CPU reading | <= 94.00 |

### Top 5 \`% Processor Time\` readings (T-003-04 answer, in order)

| Rank | Computer | TimeGenerated | CounterValue |
|------|----------|---------------|--------------|
| 1 | PRD-SQL-01 | 2026-03-11T09:15:00Z | 99.87 |
| 2 | PRD-APP-01 | 2026-03-11T09:15:00Z | 98.41 |
| 3 | PRD-WEB-01 | 2026-03-11T09:00:00Z | 97.62 |
| 4 | PRD-APP-02 | 2026-03-11T09:15:00Z | 96.15 |
| 5 | PRD-WEB-02 | 2026-03-11T09:00:00Z | 95.33 |

## Terminal answers

| Terminal | Query | Expected |
|----------|-------|----------|
| T-003-01 | \`Perf \\| project TimeGenerated, Computer, CounterName, CounterValue\` | 4 columns, that order |
| T-003-02 | \`Perf \\| project-away InstanceName, ObjectName \\| project-rename Value = CounterValue\` | TimeGenerated, Computer, CounterName, Value |
| T-003-03 | \`Perf \\| where CounterName == "% Processor Time" \\| sort by TimeGenerated desc \\| project TimeGenerated, Computer, CounterValue\` | 1152 rows, first is 2026-03-11T11:45:00Z |
| T-003-04 | \`Perf \\| where CounterName == "% Processor Time" \\| top 5 by CounterValue desc \\| project Computer, TimeGenerated, CounterValue\` | the 5 rows above, in order |

## Narrative note

Rank 3 and 5 are at **09:00** — twelve minutes *before* the 09:12Z rule change. That is deliberate: it is the
evidence that defeats the "CPU starved the agents" verdict option in \`case.json\`.
`,
});
