// ds-case001-heartbeat — Case 001 "Heartbeat Hills"
// Spec: KQL-Detective-Implementation-Spec.md §7.1
//
// Planted facts (asserted by verify.mjs):
//   Heartbeat total rows .......................... 3296
//   rows where TimeGenerated > ago(3h) ............ 260   (7 healthy x 35, 5 stopped x 3)
//   distinct Computer ............................. 12
//   5 machines' last heartbeat .................... 2026-03-11T09:15:00Z

import { QUERY_TIME, iso, timeSlots, writeDataset } from './lib.mjs';

const SPAN_START = '2026-03-10T12:00:00Z';
const SPAN_END = '2026-03-11T11:55:00Z';
const STEP_MINUTES = 5;
const OUTAGE_AT = '2026-03-11T09:15:00Z';

const COMPUTERS = [
  // Computer,        OSType,    ComputerEnvironment, ResourceGroup,   goesDark
  ['PRD-WEB-01',   'Linux',   'Production',  'rg-prod-web',  true],
  ['PRD-WEB-02',   'Linux',   'Production',  'rg-prod-web',  true],
  ['PRD-APP-01',   'Linux',   'Production',  'rg-prod-app',  true],
  ['PRD-APP-02',   'Linux',   'Production',  'rg-prod-app',  true],
  ['PRD-SQL-01',   'Windows', 'Production',  'rg-prod-data', true],
  ['PRD-WEB-03',   'Linux',   'Production',  'rg-prod-web',  false],
  ['PRD-SQL-02',   'Windows', 'Production',  'rg-prod-data', false],
  ['PRD-CACHE-01', 'Linux',   'Production',  'rg-prod-app',  false],
  ['PRD-MON-01',   'Linux',   'Production',  'rg-prod-mon',  false],
  ['DEV-WEB-01',   'Linux',   'Development', 'rg-dev',       false],
  ['DEV-APP-01',   'Linux',   'Development', 'rg-dev',       false],
  ['UAT-APP-01',   'Windows', 'UAT',         'rg-uat',       false],
];

// Agent version is stable per OS — a decoy column, like RemoteIPCountry.
const VERSION = { Linux: '1.28.11', Windows: '10.22.1011.0' };

const COLUMNS = [
  { name: 'TimeGenerated', type: 'datetime' },
  { name: 'Computer', type: 'string' },
  { name: 'OSType', type: 'string' },
  { name: 'Version', type: 'string' },
  { name: 'ComputerEnvironment', type: 'string' },
  { name: 'RemoteIPCountry', type: 'string' },
  { name: 'ResourceGroup', type: 'string' },
];

const slots = timeSlots(SPAN_START, SPAN_END, STEP_MINUTES);
const outageMs = new Date(OUTAGE_AT).getTime();

const rows = [];
for (const [computer, osType, env, rg, goesDark] of COMPUTERS) {
  for (const slot of slots) {
    if (goesDark && slot.getTime() > outageMs) continue;
    rows.push({
      TimeGenerated: iso(slot),
      Computer: computer,
      OSType: osType,
      Version: VERSION[osType],
      ComputerEnvironment: env,
      RemoteIPCountry: 'United States',
      ResourceGroup: rg,
    });
  }
}

// Sort by time then computer so data.json diffs stay readable across regenerations.
rows.sort((a, b) =>
  a.TimeGenerated === b.TimeGenerated
    ? a.Computer.localeCompare(b.Computer)
    : a.TimeGenerated.localeCompare(b.TimeGenerated)
);

writeDataset({
  datasetId: 'ds-case001-heartbeat',
  tables: { Heartbeat: rows },
  columns: { Heartbeat: COLUMNS },
  readme: `
# ds-case001-heartbeat

Generated by \`seed/seed-case001.mjs\`. Do not edit by hand.

- **queryTime:** ${QUERY_TIME} (engine must resolve \`now()\`/\`ago()\` against this)
- **Span:** ${SPAN_START} to ${SPAN_END}, one row per computer every ${STEP_MINUTES} minutes
- **Computers:** 12 (288 slots each when healthy)

## Planted facts

| Fact | Value |
|------|-------|
| Total \`Heartbeat\` rows | 3296 |
| Distinct \`Computer\` values | 12 |
| Machines that go dark | PRD-WEB-01, PRD-WEB-02, PRD-APP-01, PRD-APP-02, PRD-SQL-01 |
| Their last heartbeat | ${OUTAGE_AT} (256 rows each) |
| Healthy machines | 7, 288 rows each |
| Rows where \`TimeGenerated > ago(3h)\` | 260 = (7 x 35) + (5 x 3) |

## Terminal answers

| Terminal | Query | Expected |
|----------|-------|----------|
| T-001-01 | \`Heartbeat \\| take 10\` | 10 rows |
| T-001-02 | \`Heartbeat \\| where TimeGenerated > ago(3h)\` | 260 rows |
| T-001-03 | \`... \\| summarize Beats = count() by Computer\` | 12 rows: 7 healthy at 35, 5 dark at 3 |
| T-001-04 | \`Heartbeat \\| summarize LastSeen = max(TimeGenerated) by Computer \\| where LastSeen <= datetime(2026-03-11 09:15:00)\` | the 5 dark machines, all \`LastSeen = ${OUTAGE_AT}\` |

## Decoy columns

\`RemoteIPCountry\` is "United States" on every row and \`Version\` is constant per OS. Both exist to teach
that not every column carries signal.
`,
});
